const fields = {};

fields.pageviewFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v0: 'Campaign',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v4: 'Library Version',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v7: 'Site Country',
  v8: 'Previous Page Name',
  v9: 'Previous Page URL',
  v10: 'Page Type',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v18: 'Page Document Title',
  v32: 'Personalization Variants',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v37: 'Navigation Type',
  v38: 'Tab ID',
  v39: 'Tab Type',
  v40: 'Tab Count',
  event16: 'Redirect Count',
};

fields.clickFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v46: 'Click Type',
  v47: 'Click Name',
  v48: 'Click Label',
  v49: 'Click Count',
  event19: 'Click Count',
};

fields.customEventFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v42: 'Event Type',
  v43: 'Event Name',
  v44: 'Event Label',
  v45: 'Event Count',
  event18: 'Custom Event Count',
};

fields.formViewedFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v50: 'Form ID',
  event46: 'Form View',
};

fields.formCompleteFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v50: 'Form ID',
  v51: 'Form Inputs',
  v52: 'Form Input Count',
  v53: 'Form Selected Count',
  c14: 'Form Errors',
  c16: 'Form Interaction Path',
  event20: 'Form Start',
  event21: 'Form Complete',
  event22: 'Form Error Count',
  event23: 'Form Selected Count',
};

fields.beforeUnloadFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v19: 'Page Height',
  v20: 'Page Percent Viewed',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  v41: 'Tab Focus Count',
  v50: 'Form ID',
  v51: 'Form Inputs',
  v52: 'Form Input Count',
  v53: 'Form Selected Count',
  v55: 'Chat Online',
  v56: 'Chat Team Available',
  v57: 'Chat Visible',
  v58: 'Chat Covnersation ID',
  v59: 'Chat Playbook ID',
  v60: 'Chat Campaign ID',
  c14: 'Form Errors',
  c16: 'Form Interaction Path',
  c17: 'Forms On Page',
  event1: 'Redirect Timing',
  event2: 'App cache Timing',
  event3: 'DNS Timing',
  event4: 'TCP Timing',
  event5: 'Request Timing',
  event6: 'Response Timing',
  event7: 'Processing Timing',
  event8: 'On Load Timing',
  event9: 'Page Load Timing',
  event10: 'Page Scrolled 10%',
  event11: 'Page Scrolled 25%',
  event12: 'Page Scrolled 50%',
  event13: 'Page Scrolled 75%',
  event14: 'Page Scrolled 95%',
  event15: 'Page Scrolled 100%',
  event17: 'Tab Click',
  event20: 'Form Start',
  event21: 'Form Complete',
  event22: 'Form Error Count',
  event23: 'Form Selected Count',
  event34: 'Sidebar Opened',
  event35: 'Sidebar Closed',
  event36: 'Playbook Clicked',
  event37: 'Playbook Dismissed',
  event38: 'Conversation Started',
  event39: 'Message Sent',
  event40: 'Message Receieved',
  event41: 'Email Captured',
  event42: 'Phone Captured',
  event43: 'Meeting Requested',
  event44: 'Meeting Booked',
  event45: 'Forms On Page'
};

fields.videoFields = {
  url: 'Test URL',
  rs: 'Report Suite',
  status: 'Status Code',
  playerName: 'Media Player Name',
  name: 'Video Name',
  length: 'Video Length',
  pageName: 'Page Name',
  ch: 'Site Section',
  server: 'Server',
  v1: 'Hit Type',
  v2: 'Timestamp',
  v3: 'Pageview ID',
  v5: 'Adobe Analytics ID',
  v6: 'Google Analytics ID',
  v13: 'Page Protocol',
  v14: 'Page Domain',
  v15: 'Page Path',
  v16: 'Page Query String',
  v17: 'Page Fragment',
  v35: 'Procore ID',
  v36: 'Procore User Type',
  events: 'Events',
  event24: 'Video View',
  event25: 'Video Play',
  event26: 'Video Pause',
  event27: 'Video Complete',
  event28: 'Video Time Played',
  event29: 'Video 10% Watched',
  event30: 'Video 25% Watched',
  event31: 'Video 50% Watched',
  event32: 'Video 75% Watched',
  event33: 'Video 95% Watched',
};

module.exports = fields;
